### ISSUE TITLE
Wrong homeserver.yaml

### ISSUE THREAD

**Issue by mucan54** [attraktorhh/matrix#4]
I had this in my homeserver.yaml file:

```
root@e41a256900d4:/data/config# cat homeserver.yaml
server_name: matrix.energetisch.dev

listeners:
  - port: 8008
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]

report_stats: False

logging:
  - module: synapse.storage.SQL
    level: INFO

use_x_forwarded: true
bind_addresses: ['127.0.0.1']

trusted_key_servers:
  - server_name: "matrix.org"
suppress_key_server_warning: true

enable_registration: false
password_config:
  enabled: false

admin_contact: 'mailto:admin@matrix.energetisch.dev'

experimental_features:
  msc3861:
    enabled: true

    # Synapse will call `{issuer}/.well-known/openid-configuration` to get the OIDC configuration
    #issuer: https://mas.matrix.energetisch.dev
    issuer: http://synapse-mass-authentication-service:8080

    # Matches the `client_id` in the auth service config
    client_id: 0000000000000000000SYNAPSE
    # Matches the `client_auth_method` in the auth service config
    client_auth_method: client_secret_basic
    # Matches the `client_secret` in the auth service config
    client_secret: "your-synapse-mas-secret"

    # Matches the `matrix.secret` in the auth service config
    admin_token: "your-synapse-api-admin-token"

    # URL to advertise to clients where users can self-manage their account
    account_management_url: "https://keycloak.energetisch.dev/realms/{{KEYCLOAK_REALM_IDENTIFIER}}/account"
root@e41a256900d4:/data/config# 
```
